app:
  server:
    port: 服务器端口
    domainUrl: https://xx
    registerCode: "admin"
    userFile: "/data/users.txt"
  wx:
    token: 微信token
    appId: xx
    appSecret: xxx
    msgPath: /app/wchatgpt/msg
  turing:
    userId: xxx
    apiKey: xxx
    keyword: xxx
  openai:
    skToken: xxx
    keyword: xxx
server:
  port: 8080
  servlet:
    context-path: /wchatgpt-be/
