app:
  db:
    url: xxx
    username: xxx
    password: xxx
  customer:
    wx:
      id: xxx
      qr_code: xx
  server:
    port: 服务器端口
    domain-url: http://127.0.0.1:8080/wchatgpt-be
    registerCode: "admin"
    userFile: "/Users/jinmancang1/work/repository/wchatgpt/users.txt"
  wx:
    token: 微信token
    appId: xx
    appSecret: xxx
    msgPath: /app/wchatgpt/msg
  turing:
    userId: xxx
    apiKey: xxx
    keyword: xxx
  openai:
    skToken: xxx
    keyword: xxx
    img-dir: /tmp/
server:
  port: 8080
  servlet:
    context-path: /wchatgpt-be/
spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resources/,file:${app.openai.img-dir}
  mvc:
    dispatch-options-request: true
  datasource:
    hikari:
      jdbc-url: ${app.db.url}
      username: ${app.db.username}
      password: ${app.db.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${app.db.url}
    username: ${app.db.username}
    password: ${app.db.password}
