app:
  server:
    port: 8080
  turing:
    userId: ligson
    apiKey: f835f4c0880c4ec5bc8eab730ad579c0
    keyword: nmd
  openai:
    skToken: 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
    keyword: tmd
