app:
  customer:
    wx:
      id: xxx
      qr_code: xx
  server:
    port: 服务器端口
    domain-url: https://xx
    registerCode: "admin"
    userFile: "/Users/jinmancang1/work/repository/wchatgpt/users.txt"
  wx:
    token: 微信token
    appId: xx
    appSecret: xxx
    msgPath: /app/wchatgpt/msg
  turing:
    userId: xxx
    apiKey: xxx
    keyword: xxx
  openai:
    skToken: xxx
    keyword: xxx
    img-dir: /tmp/
server:
  port: 8080
  servlet:
    context-path: /wchatgpt-be/
spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resources/,file:${app.openai.img-dir}
