app:
  db:
    url: xxx
    username: xxx
    password: xxx
  redis:
    host: 127.0.0.1
    port: 6379
    password: password
  customer:
    wx:
      id: xxx
      qr_code: xx
  server:
    domain-url: http://127.0.0.1:8080/wchatgpt-be
    register-code: "admin"
    user-file: "/Users/jinmancang1/work/repository/wchatgpt/users.txt"
  openai:
    sk-token: xxx
    img-dir: /tmp/
server:
  port: 8080
  servlet:
    context-path: /wchatgpt-be/
spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/resources/,file:${app.openai.img-dir}
  mvc:
    dispatch-options-request: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: false
        type:
          descriptor:
            sql:
              log: true
  datasource:
    hikari:
      jdbc-url: ${app.db.url}
      username: ${app.db.username}
      password: ${app.db.password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: select 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${app.db.url}
    username: ${app.db.username}
    password: ${app.db.password}
  data:
    redis:
      host: ${app.redis.host}
      port: ${app.redis.port}
      password: ${app.redis.password}
logging:
  level:
    org.ligson: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
